const TOP_LEVEL_CATEGORIES: string[] = [
    "Bank Fees",
    "Cash Advance",
    "Community",
    "Food and Drink",
    "Healthcare",
    "Interest",
    "Payment",
    "Recreation",
    "Service",
    "Shops",
    "Tax",
    "Transfer",
    "Travel",
];

const SUB_CATEGORIES: { [key: string]: string[] } = {
    "Bank Fees": [
        "ATM",
        "Cash Advance",
        "Excess Activity",
        "Foreign Transaction",
        "Fraud Dispute",
        "Insufficient Funds",
        "Late Payment",
        "Overdraft",
        "Wire Transfer",
    ],
    "Cash Advance": [],
    "Community": [
        "Animal Shelter",
        "Assisted Living Services",
        "Cemetery",
        "Courts",
        "Day Care and Preschools",
        "Disabled Persons Services",
        "Drug and Alcohol Services",
        "Education",
        "Government Departments and Agencies",
        "Government Lobbyists",
        "Housing Assistance and Shelters",
        "Law Enforcement",
        "Libraries",
        "Military",
        "Organizations and Associations",
        "Post Offices",
        "Public and Social Services",
        "Religious",
        "Senior Citizen Services",
    ],
    "Food and Drink": [
        "Bar",
        "Breweries",
        "Internet Cafes",
        "Nightlife",
        "Restaurants",
    ],
    "Healthcare": ["Healthcare Services", "Physicians"],
    "Interest": ["Interest Charged", "Interest Earned"],
    "Payment": ["Credit Card", "Loan", "Rent"],
    "Recreation": [
        "Arts and Entertainment",
        "Athletic Fields",
        "Baseball",
        "Basketball",
        "Batting Cages",
        "Boating",
        "Campgrounds and RV Parks",
        "Canoes and Kayaks",
        "Combat Sports",
        "Cycling",
        "Dance",
        "Equestrian",
        "Football",
        "Go Carts",
        "Golf",
        "Gun Ranges",
        "Gymnastics",
        "Gyms and Fitness Centers",
        "Hiking",
        "Hockey",
        "Hot Air Balloons",
        "Hunting and Fishing",
        "Landmarks",
        "Miniature Golf",
        "Outdoors",
        "Paintball",
        "Parks",
        "Personal Trainers",
        "Race Tracks",
        "Racquet Sports",
        "Racquetball",
        "Rafting",
        "Recreation Centers",
        "Rock Climbing",
        "Running",
        "Scuba Diving",
        "Skating",
        "Skydiving",
        "Snow Sports",
        "Soccer",
        "Sports and Recreation Camps",
        "Sports Clubs",
        "Stadiums and Arenas",
        "Swimming",
        "Tennis",
        "Water Sports",
        "Yoga and Pilates",
        "Zoo",
    ],
    "Service": [
        "Advertising and Marketing",
        "Agriculture and Forestry",
        "Art Restoration",
        "Art and Graphic Design",
        "Audiovisual",
        "Automation and Control Systems",
        "Automotive",
        "Business Services",
        "Business and Strategy Consulting",
        "Cable",
        "Chemicals and Gasses",
        "Cleaning",
        "Computers",
        "Construction",
        "Credit Counseling and Bankruptcy Services",
        "Dating and Escort",
        "Employment Agencies",
        "Engineering",
        "Entertainment",
        "Events and Event Planning",
        "Financial",
        "Food and Beverage",
        "Funeral Services",
        "Geological",
        "Home Improvement",
        "Household",
        "Human Resources",
        "Immigration",
        "Import and Export",
        "Industrial Machinery and Vehicles",
        "Insurance",
        "Internet Services",
        "Leather",
        "Legal",
        "Logging and Sawmills",
        "Machine Shops",
        "Management",
        "Manufacturing",
        "Media",
        "Moving",
        "Organizations and Associations",
        "Real Estate",
        "Rental",
        "Repairs",
        "Security",
        "Storage",
        "Subscription",
        "Tailors",
        "Telecommunication Services",
        "Textiles",
        "Tourist Information and Services",
        "Transportation",
        "Travel Agents and Tour Operators",
        "Utilities",
        "Veterinarians",
        "Water and Waste Management",
        "Web Design and Development",
        "Welding",
    ],
    "Shops": [
        "Adult",
        "Antiques",
        "Arts and Crafts",
        "Auctions",
        "Automotive",
        "Beauty Products",
        "Bicycles",
        "Boat Dealers",
        "Bookstores",
        "Cards and Stationery",
        "Children",
        "Clothing and Accessories",
        "Computers and Electronics",
        "Construction Supplies",
        "Convenience Stores",
        "Costumes",
        "Dance and Music",
        "Department Stores",
        "Digital Purchase",
        "Discount Stores",
        "Electrical Equipment",
        "Equipment Rental",
        "Flea Markets",
        "Florists",
        "Food and Beverage Store",
        "Fuel Dealer",
        "Furniture and Home Decor",
        "Gift and Novelty",
        "Glasses and Optometrist",
        "Hardware Store",
        "Hobby and Collectibles",
        "Industrial Supplies",
        "Jewelry and Watches",
        "Lawn and Garden",
        "Luggage",
        "Marine Supplies",
        "Music, Video and DVD",
        "Musical Instruments",
        "Newsstands",
        "Office Supplies",
        "Outlet",
        "Pawn Shops",
        "Pets",
        "Pharmacies",
        "Photos and Frames",
        "Shopping Centers and Malls",
        "Sporting Goods",
        "Supermarkets and Groceries",
        "Tobacco",
        "Toys",
        "Vintage and Thrift",
        "Warehouses and Wholesale Stores",
        "Wedding and Bridal",
        "Wholesale",
    ],
    "Tax": ["Payment", "Refund"],
    "Transfer": [
        "ACH",
        "Billpay",
        "Check",
        "Credit",
        "Debit",
        "Deposit",
        "Internal Account Transfer",
        "Keep the Change Savings Program",
        "Payroll",
        "Save As You Go",
        "Third Party",
        "Wire",
        "Withdrawal",
    ],
    "Travel": [
        "Airlines and Aviation Services",
        "Airports",
        "Boat",
        "Bus Stations",
        "Car Service",
        "Car and Truck Rentals",
        "Charter Buses",
        "Cruises",
        "Gas Stations",
        "Heliports",
        "Limos and Chauffeurs",
        "Lodging",
        "Parking",
        "Public Transportation Services",
        "Rail",
        "Taxi",
        "Tolls and Fees",
        "Transportation Centers",
    ],
};

export interface Transaction {
    id: string;
    date: Date;
    type: 'income' | 'expense';
    amount: number;
    category: string[];
    description: string;
}

export { TOP_LEVEL_CATEGORIES, SUB_CATEGORIES };